const ONE_THOUSAND = 1_000;
const MS_PER_SEC = ONE_THOUSAND;
const SEC_PER_MIN = 60;
const SEC_PER_HOUR = SEC_PER_MIN * 60;
const MS_PER_HOUR = MS_PER_SEC * SEC_PER_HOUR;
const MIN_PER_HOUR = 60;

export {
  ONE_THOUSAND,
  MS_PER_SEC,
  SEC_PER_HOUR,
  SEC_PER_MIN,
  MS_PER_HOUR,
  MIN_PER_HOUR,
};
