const color = {
  PRIMARY_BUTTON: "#3C91E6",
  PRIMARY_BUTTON_PRESSED: "#003061",

  CARD_BUTTON_BORDER: "#003061",
  CARD_BUTTON_PRESSED: "#000000",
  CARD_BUTTON_BACKGROUND: "#FFFFFF",

  SECONDARY_BUTTON: "#FFFFFF",

  PRIMARY_TEXT: "#003061",
  SECONDARY_TEXT: "#3C91E6",
  TERTIARY_TEXT: "#8FC7FF",

  CUP_COLOR: "#003061",

  APP_PRIMARY_BACKGROUND_FIRST_GRADIENT: "#FFFFFF",
  APP_PRIMARY_BACKGROUND_SECOND_GRADIENT: "#CCE7FF",
  APP_SECONDARY_BACKGROUND: "#516CC9",
};

const shadow = {
  shadowColor: color.SECONDARY_TEXT,
  shadowOffset: { width: 5, height: 5 },
  shadowOpacity: 0.2,
  shadowRadius: 5,
};

export { color, shadow };
